=== dxw/room-usage-dashboard/tests/schema/rooms.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Rooms",
  "description": "A list of rooms and their associated calendars",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "slug": {
        "description": "A unique slug identifying this room",
        "type": "string",
        "pattern": "^[a-z_]+$"
      },
      "name": {
        "description": "The name of this room",
        "type": "string"
      },
      "css_class": {
        "description": "The CSS class used to apply this room's colours",
        "type": "string",
        "pattern": "^[a-z-_]+$"
      },
      "gcal_identifier": {
        "description": "The unique identifier for the Google calendar representing this room",
        "type": "string",
        "pattern": "^dxw\\.com_[0-9a-z]+@resource\\.calendar\\.google\\.com$"
      },
      "presence_colour_rgb": {
        "description": "An array of RGB values to set the identifying colour of this room's free/busy indicator",
        "type": "array",
        "items": {
          "type": "integer",
          "exclusiveMinimum": 0,
          "exclusiveMaximum": 255
        },
        "minItems": 3,
        "maxItems": 3
      }
    },
    "required": ["slug", "name", "css_class", "gcal_identifier"],
    "additionalProperties": false
  },
  "minItems": 1
}

=== dxw/room-usage-dashboard/spec/test_rooms.json
[
  {
    "slug": "hoxton_test01",
    "name": "Hoxton Test01 Meeting Room",
    "css_class": "room__hoxton-ground",
    "gcal_identifier": "dxw.com_2d36303034323634352d353334@resource.calendar.google.com"
  },
  {
    "slug": "hoxton_test02",
    "name": "Hoxton Test02 Meeting Room",
    "css_class": "room__hoxton-hide",
    "gcal_identifier": "dxw.com_3936393930353336393539@resource.calendar.google.com"
  },
  {
    "slug": "hoxton_test03",
    "name": "Hoxton Test03 Meeting Room",
    "css_class": "room__hoxton-wellbeing",
    "gcal_identifier": "dxw.com_3437393236383531353437@resource.calendar.google.com"
  },
  {
    "slug": "leeds_test01",
    "name": "Leeds Test01 Meeting Room",
    "css_class": "room__leeds-mustard",
    "gcal_identifier": "dxw.com_18862haevrjfegh8jgp0540eipjn86gb74s3ac9n6spj6c9l6g@resource.calendar.google.com",
    "presence_colour_rgb": [168, 87, 17]
  },
  {
    "slug": "leeds_test02",
    "name": "Leeds Test02 Meeting Room",
    "css_class": "room__leeds-peacock",
    "gcal_identifier": "dxw.com_188326f7n3qtqiqjmqptmimskfsmu6g86cp38dhk68s34@resource.calendar.google.com",
    "presence_colour_rgb": [50, 139, 168]
  },
  {
    "slug": "leeds_test03",
    "name": "Leeds Test03 Meeting Room",
    "css_class": "room__leeds-plum",
    "gcal_identifier": "dxw.com_188al9agrcprmgaki2tcu1r5i0eim6gb64o30dpj6opj4d9g6s@resource.calendar.google.com",
    "presence_colour_rgb": [59, 11, 59]
  },
  {
    "slug": "leeds_test04",
    "name": "Leeds Test04 Meeting Room",
    "css_class": "room__leeds-green",
    "gcal_identifier": "dxw.com_1887p1bi29mkqi6sgnh07chkatufk6ga64o32chj70q32dhn@resource.calendar.google.com",
    "presence_colour_rgb": [20, 87, 15]
  },
  {
    "slug": "zoom_test01",
    "name": "Zoom Test01 Meeting Room",
    "css_class": "room__zoom-a",
    "gcal_identifier": "dxw.com_188fvcktkaps6grlmf2sr2lhn6nnk@resource.calendar.google.com"
  },
  {
    "slug": "zoom_test02",
    "name": "Zoom Test02 Meeting Room",
    "css_class": "room__zoom-b",
    "gcal_identifier": "dxw.com_188ejcf5p6aluidmn9650faudo5eg@resource.calendar.google.com"
  },
  {
    "slug": "zoom_test03",
    "name": "Zoom Test03 Meeting Room",
    "css_class": "room__zoom-c",
    "gcal_identifier": "dxw.com_188drohphtvniidqkrud8jujqvvqu@resource.calendar.google.com"
  }
]

=== dxw/room-usage-dashboard/rooms.json
[
  {
    "slug": "hoxton_ground",
    "name": "Main Meeting Room",
    "css_class": "room__hoxton-ground",
    "gcal_identifier": "dxw.com_2d36303034323634352d353334@resource.calendar.google.com"
  },
  {
    "slug": "hoxton_hide",
    "name": "The Hide",
    "css_class": "room__hoxton-hide",
    "gcal_identifier": "dxw.com_3936393930353336393539@resource.calendar.google.com"
  },
  {
    "slug": "hoxton_wellbeing",
    "name": "Wellbeing Room",
    "css_class": "room__hoxton-wellbeing",
    "gcal_identifier": "dxw.com_3437393236383531353437@resource.calendar.google.com"
  },
  {
    "slug": "leeds_mustard",
    "name": "Col. Mustard",
    "css_class": "room__leeds-mustard",
    "gcal_identifier": "dxw.com_18862haevrjfegh8jgp0540eipjn86gb74s3ac9n6spj6c9l6g@resource.calendar.google.com",
    "presence_colour_rgb": [168, 87, 17]
  },
  {
    "slug": "leeds_peacock",
    "name": "Dr. Peacock",
    "css_class": "room__leeds-peacock",
    "gcal_identifier": "dxw.com_188326f7n3qtqiqjmqptmimskfsmu6g86cp38dhk68s34@resource.calendar.google.com",
    "presence_colour_rgb": [50, 139, 168]
  },
  {
    "slug": "leeds_plum",
    "name": "Prof. Plum",
    "css_class": "room__leeds-plum",
    "gcal_identifier": "dxw.com_188al9agrcprmgaki2tcu1r5i0eim6gb64o30dpj6opj4d9g6s@resource.calendar.google.com",
    "presence_colour_rgb": [59, 11, 59]
  },
  {
    "slug": "leeds_green",
     "name": "Revd. Green",
     "css_class": "room__leeds-green",
     "gcal_identifier": "dxw.com_1887p1bi29mkqi6sgnh07chkatufk6ga64o32chj70q32dhn@resource.calendar.google.com",
     "presence_colour_rgb": [20, 87, 15]
  },
  {
    "slug": "zoom_a",
    "name": "Zoom Call A",
    "css_class": "room__zoom-a",
    "gcal_identifier": "dxw.com_188fvcktkaps6grlmf2sr2lhn6nnk@resource.calendar.google.com"
  },
  {
    "slug": "zoom_b",
    "name": "Zoom Call B",
    "css_class": "room__zoom-b",
    "gcal_identifier": "dxw.com_188ejcf5p6aluidmn9650faudo5eg@resource.calendar.google.com"
  },
  {
    "slug": "zoom_c",
    "name": "Zoom Call C",
    "css_class": "room__zoom-c",
    "gcal_identifier": "dxw.com_188drohphtvniidqkrud8jujqvvqu@resource.calendar.google.com"
  }
]
